services:
  - type: web
    name: hospital-management-system
    runtime: python
    pythonVersion: 3.11
    plan: free
    startCommand: gunicorn hospital_management_system.wsgi --bind 0.0.0.0:$PORT
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
